server:
  port: 8088
spring:
  datasource:                                                                #数据源相关配置
    url: jdbc:mysql://192.168.133.133:3306/xufeifan?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: 123456
  redis:
    database: 1
    host: 192.168.133.133
    port: 6379
    password: 123456
    #Redis 哨兵模式
#    database: 1
#    password: 123456
#    sentinel:
#      master: imooc-master
#      nodes: 192.168.133.133:26379
#    Redis 集群模式
#     password: 123456
#     cluster:
#      nodes: 192.168.133.133:26379

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl